# Generated by Django 2.2 on 2019-05-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialTennis', '0003_auto_20190421_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='kind',
            field=models.TextField(choices=[('plan', 'meet')], default='meet'),
            preserve_default=False,
        ),
    ]
