# Generated by Django 2.2 on 2019-06-02 03:38
# edited by Dan afterward

from django.db import migrations, models
import datetime

def created_at_to_date(apps, schema_editor):
    Event = apps.get_model('SocialTennis', 'Event')
    db_alias = schema_editor.connection.alias
    for i in Event.objects.using(db_alias).all():
        i.date = i.created_at.date()
        i.save()

class Migration(migrations.Migration):

    dependencies = [
        ('SocialTennis', '0004_event_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.RunPython(created_at_to_date),
    ]
