# Generated by Django 2.2 on 2019-06-02 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialTennis', '0005_auto_20190602_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
    ]
