# Generated by Django 2.2 on 2019-06-11 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SocialTennis', '0006_remove_event_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='kind',
            field=models.TextField(choices=[('plan', 'plan'), ('meet', 'meet')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='server',
            field=models.TextField(choices=[('me', 'me'), ('them', 'them'), ('neither', 'neither')]),
        ),
    ]
